backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "images"

collections:
  - name: "service"
    label: "Service"
    folder: "_services/"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "service",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
